/*
 * EDMA.c
 *
 *  Created on: Oct 12, 2020
 *      Author: Luis Pérez
 *     Version: 1.0
 */

#include "EDMA.h"

unsigned short int ADConversion[10];
unsigned char RTCregister[20];

void DMA_InitPeripheral(void){
	SIM_SCGC7 |= SIM_SCGC7_DMA_MASK;
	SIM_SCGC6 |= SIM_SCGC6_DMAMUX_MASK;
}

void DMA_SetChannel0(void){
	//PIT0 GENERATES PERIODIC TRIGGER EVENTS TO THE DMAMUX TO STORE THE VALUES OF CURRENT TIME (HOURS, MINUTES).
	//DMA CHANNEL NUMBER -- PIT CHANNEL
	//   DMA CHANNEL0    -- PIT_CHANNEL0
	
	DMAMUX_CHCFG0 = 0x00;
	DMA_TCD0_CITER_ELINKNO = DMA_CITER_ELINKNO_CITER(10);
	DMA_TCD0_BITER_ELINKNO = DMA_BITER_ELINKNO_BITER(10);
	DMA_TCD0_NBYTES_MLNO = 0x02;
	DMA_TCD0_SADDR = (uint32_t)&time+0x04;
	DMA_TCD0_SOFF = 0x00;
	DMA_TCD0_SLAST = 0x00;
	DMA_TCD0_DADDR = (uint32_t)RTCregister;
	DMA_TCD0_DOFF = 0x01;
	DMA_TCD0_DLASTSGA = -20;
	DMA_TCD0_ATTR = DMA_ATTR_SSIZE(1) | DMA_ATTR_DSIZE(0);
	DMA_ERQ |= DMA_ERQ_ERQ0_MASK;
	DMAMUX_CHCFG0 = DMAMUX_CHCFG_ENBL_MASK | DMAMUX_CHCFG_TRIG_MASK | (DMAMUX_CHCFG_SOURCE_MASK & 58);
}

void DMA_SetChannel4(void){
	//AFTER THE COMPLETE CONVERSION OF THE ADC, A DMA REQUEST IS ASKED TO STORE THE DATA RESULT.
	//SOURCE NUMBER -- SOURCE MODULE
	//      40      --     ADC0
	
	DMAMUX_CHCFG4 = 0x00;
	DMA_TCD4_CITER_ELINKNO = DMA_CITER_ELINKNO_CITER(10);
	DMA_TCD4_BITER_ELINKNO = DMA_BITER_ELINKNO_BITER(10);
	DMA_TCD4_NBYTES_MLNO = 0x02;
	DMA_TCD4_SADDR = (uint32_t)&ADC0_RA;
	DMA_TCD4_SOFF = 0x00;
	DMA_TCD4_SLAST = 0x00;
	DMA_TCD4_DADDR = (uint32_t)ADConversion;
	DMA_TCD4_DOFF = 0x02;
	DMA_TCD4_DLASTSGA = -20;
	DMA_TCD4_ATTR = DMA_ATTR_SSIZE(1) | DMA_ATTR_DSIZE(1);
	DMA_ERQ |= DMA_ERQ_ERQ4_MASK;
	DMAMUX_CHCFG4 = DMAMUX_CHCFG_ENBL_MASK | (DMAMUX_CHCFG_SOURCE_MASK & 40);
}
